//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Notice_Privacy
    {
        public int Notice_Privacy_Id { get; set; }
        public string Notice_Privacy_Title { get; set; }
        public string Notice_Privacy_Content { get; set; }
    }
}
