//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Carts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Carts()
        {
            this.cat_Orders = new HashSet<cat_Orders>();
        }
    
        public int Cart_Id { get; set; }
        public string Cart_Json_Config { get; set; }
        public System.DateTime Cart_Creation_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_Orders> cat_Orders { get; set; }
    }
}
