//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Coupons
    {
        public int Coupon_Id { get; set; }
        public string Coupon_Code { get; set; }
        public Nullable<decimal> Coupon_Amount { get; set; }
        public Nullable<decimal> Coupon_Discount { get; set; }
        public System.DateTime Coupon_Creation_Date { get; set; }
        public System.DateTime Coupon_Expiration_Date { get; set; }
        public Nullable<System.DateTime> Coupon_Use_Date { get; set; }
    }
}
