//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Social_Media
    {
        public int Social_Media_Id { get; set; }
        public string Social_Media_Name { get; set; }
        public string Social_Media_Awesome_Font { get; set; }
        public string Social_Media_Url { get; set; }
        public string Social_Media_Tab { get; set; }
    }
}
