//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Reviews
    {
        public int Review_Id { get; set; }
        public int Product_Id { get; set; }
        public int Review_Score { get; set; }
    
        public virtual cat_Products cat_Products { get; set; }
    }
}
