//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Coupons
    {
        public int Coupon_Id { get; set; }
        public string Coupon_Code { get; set; }
        public Nullable<decimal> Coupon_Amount { get; set; }
        public Nullable<decimal> Coupon_Discount { get; set; }
        public System.DateTime Coupon_Creation_Date { get; set; }
        public System.DateTime Coupon_Expiration_Date { get; set; }
        public Nullable<System.DateTime> Coupon_Use_Date { get; set; }
        public string Specific_Rule_Json_Config { get; set; }
    }
}
