//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Admin_Login
    {
        public int Admin_Login_Id { get; set; }
        public string Admin_Login_Username { get; set; }
        public string Admin_Login_Password { get; set; }
    }
}
