//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Orders
    {
        public int Order_Id { get; set; }
        public int Cart_Id { get; set; }
        public string Order_Client_Name { get; set; }
        public string Order_Client_Email { get; set; }
        public string Order_Client_Phone { get; set; }
        public string Order_Client_Address1 { get; set; }
        public string Order_Client_Address2 { get; set; }
        public string Order_Client_Province { get; set; }
        public string Order_Client_City { get; set; }
        public string Order_Client_Zip { get; set; }
        public string Order_Client_Comments { get; set; }
        public System.DateTime Order_Creation_Date { get; set; }
        public Nullable<System.DateTime> Order_Delivered_Date { get; set; }
        public string Order_Openpay_ChargeId { get; set; }
        public string Order_Tracking_Id { get; set; }
    
        public virtual cat_Carts cat_Carts { get; set; }
    }
}
