//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Product_Galery_Images
    {
        public int Product_Galery_Image_Id { get; set; }
        public int Product_Id { get; set; }
        public string Product_Galery_Image_Img { get; set; }
        public int Product_Galery_Image_Order { get; set; }
    
        public virtual cat_Products cat_Products { get; set; }
    }
}
