//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base(ConnectionString())
        {
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	protected static string ConnectionString()
        {
            string database = ConfigurationManager.AppSettings["Database"];
            if (database.Length == 0)
            {
                database = "CMS_Dev-Cart";
            }
            string ConnectionString = ConfigurationManager.ConnectionStrings["Entities"].ConnectionString.Replace("{CMS_Dev-Cart}", database);
            return ConnectionString;
        }
    
        public virtual DbSet<cat_About_Us_Sections> cat_About_Us_Sections { get; set; }
        public virtual DbSet<cat_Admin_Login> cat_Admin_Login { get; set; }
        public virtual DbSet<cat_Carts> cat_Carts { get; set; }
        public virtual DbSet<cat_Offers_Image> cat_Offers_Image { get; set; }
        public virtual DbSet<cat_Orders> cat_Orders { get; set; }
        public virtual DbSet<cat_Product_Galery_Images> cat_Product_Galery_Images { get; set; }
        public virtual DbSet<cat_Products> cat_Products { get; set; }
        public virtual DbSet<cat_Slider_Images> cat_Slider_Images { get; set; }
        public virtual DbSet<cat_Categories> cat_Categories { get; set; }
        public virtual DbSet<cat_Reviews> cat_Reviews { get; set; }
        public virtual DbSet<cat_Sepomex> cat_Sepomex { get; set; }
        public virtual DbSet<vw_Orders> vw_Orders { get; set; }
        public virtual DbSet<vw_Products> vw_Products { get; set; }
        public virtual DbSet<vw_Sepomex_Info> vw_Sepomex_Info { get; set; }
    }
}
