//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Orders
    {
        public int Order_Id { get; set; }
        public int Cart_Id { get; set; }
        public string Cart_Json_Config { get; set; }
        public string Order_Client_Name { get; set; }
        public string Order_Client_Email { get; set; }
        public string Order_Client_Phone { get; set; }
        public string Order_Client_Address1 { get; set; }
        public string Order_Client_Address2 { get; set; }
        public string Order_Client_Province { get; set; }
        public string Order_Client_City { get; set; }
        public string Order_Client_Zip { get; set; }
        public string Order_Client_Comments { get; set; }
        public System.DateTime Order_Creation_Date { get; set; }
        public Nullable<System.DateTime> Order_Delivered_Date { get; set; }
        public string Order_Openpay_ChargeId { get; set; }
        public string Order_Payment_Status { get; set; }
        public string Order_Tracking_Id { get; set; }
    }
}
