//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.dev_cart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Products
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public decimal Product_Price { get; set; }
        public Nullable<decimal> Product_Disscount { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Category_Name { get; set; }
        public string Product_Img { get; set; }
        public string Product_Description { get; set; }
        public string Product_Configurations { get; set; }
        public Nullable<System.DateTime> Product_Creation_Date { get; set; }
        public bool Product_Released { get; set; }
        public int Product_Stock { get; set; }
        public decimal Product_Ranking { get; set; }
        public Nullable<decimal> Product_Price_Total { get; set; }
        public Nullable<bool> Product_Is_New { get; set; }
    }
}
